from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        # Title
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 10, 'DIAGNOX | AI Medical Report', align='C')
        self.ln(5)
        
        # Subtitle
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'AI-Generated Clinical Analysis', align='C')
        self.ln(15)
        self.line(10, 30, 200, 30) # Draw a line
        self.ln(5)

    def footer(self):
        # Go to 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(0, 0, 0) # Black
        self.cell(0, 10, self.clean_text(title), 0, 1)
        self.ln(2)

    def chapter_body(self, body):
        self.set_font('Helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, self.clean_text(body))
        self.ln(5)

    def add_alert(self, text):
        # Red text for alerts
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(200, 50, 50) # Red
        # We manually add a bullet point "-" instead of an emoji
        self.cell(0, 6, f"- {self.clean_text(text)}", ln=True)
        self.set_text_color(0, 0, 0) # Reset

    def clean_text(self, text):
        """
        Removes emojis and unsupported characters by encoding to latin-1 
        and ignoring errors. This prevents the PDF engine from crashing.
        """
        if not text:
            return ""
        # 1. Replace common problematic chars
        text = text.replace('’', "'").replace('“', '"').replace('”', '"')
        # 2. Force convert to Latin-1 compatible text (strips emojis)
        return text.encode('latin-1', 'ignore').decode('latin-1')

def create_pdf_report(data):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. METADATA
    patient = data.get('metadata', {}).get('patient_name', 'Unknown')
    date = data.get('metadata', {}).get('report_date', 'Unknown')
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, pdf.clean_text(f"Patient Name: {patient}"), ln=True)
    pdf.cell(0, 8, pdf.clean_text(f"Date of Report: {date}"), ln=True)
    pdf.ln(5)
    
    # 2. EXECUTIVE SUMMARY
    pdf.chapter_title("Executive Summary")
    pdf.chapter_body(data.get('patient_summary', 'No summary available.'))
    
    # 3. CRITICAL FINDINGS (Removed Emoji from Title)
    findings = data.get('critical_findings', [])
    if findings:
        pdf.chapter_title("Critical Findings")
        for item in findings:
            pdf.add_alert(item)
        pdf.ln(5)
            
    # 4. RECOMMENDATIONS (Removed Emoji from Title)
    recs = data.get('recommendations', {})
    if recs:
        pdf.chapter_title("Recommended Actions")
        
        if 'medical_next_steps' in recs:
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(0, 8, "Medical Next Steps:", ln=True)
            pdf.set_font('Helvetica', '', 11)
            for step in recs['medical_next_steps']:
                pdf.cell(0, 6, f"- {pdf.clean_text(step)}", ln=True)
            pdf.ln(3)

        if 'lifestyle_actions' in recs:
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(0, 8, "Lifestyle Adjustments:", ln=True)
            pdf.set_font('Helvetica', '', 11)
            for step in recs['lifestyle_actions']:
                pdf.cell(0, 6, f"- {pdf.clean_text(step)}", ln=True)
    
    # 5. DISCLAIMER
    pdf.ln(15)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by AI (DIAGNOX) and is for informational purposes only.")
    
    # Output: Cast to BYTES to satisfy Streamlit
    return bytes(pdf.output(dest='S'))